/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xtranslator;


import java.awt.Color;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.json.JSONArray;

/**
 *
 * @author henry
 */
public class MainTranslator extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainTranslator() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        outputpane.setEditable(false);

    }

    public void Timer() {
        Timer t2 = new Timer();
        t2.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {
                String waktunow = new SimpleDateFormat("10" + "ss").format(new java.util.Date());
                tesdinamis.setkGradientFocus(Integer.valueOf(waktunow));
            }
        }, 0, 1000);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tesdinamis = new keeptoo.KGradientPanel();
        ConstraintSheet = new javax.swing.JPanel();
        SheetStart = new javax.swing.JPanel();
        bt_starttranslating = new javax.swing.JLabel();
        SheetConfig = new javax.swing.JPanel();
        asalbahasa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        hasilbahasa = new javax.swing.JComboBox<>();
        wklikttranslate = new keeptoo.KGradientPanel();
        btntranslate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_clearall = new javax.swing.JLabel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        btnclose = new javax.swing.JLabel();
        btnminimize = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sheetinput = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        indikatorinput = new javax.swing.JLabel();
        scrollinput = new javax.swing.JScrollPane();
        inputpane = new javax.swing.JTextArea();
        labelinput1 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        indikatoroutput = new javax.swing.JLabel();
        scrolloutput = new javax.swing.JScrollPane();
        outputpane = new javax.swing.JTextArea();
        labelinput2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tesdinamis.setkBorderRadius(50);
        tesdinamis.setkEndColor(new java.awt.Color(239, 50, 217));
        tesdinamis.setkGradientFocus(900);
        tesdinamis.setkStartColor(new java.awt.Color(137, 255, 253));
        tesdinamis.setOpaque(false);

        ConstraintSheet.setOpaque(false);
        ConstraintSheet.setLayout(new java.awt.CardLayout());

        SheetStart.setOpaque(false);

        bt_starttranslating.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        bt_starttranslating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/icons8-google-translate-64.png"))); // NOI18N
        bt_starttranslating.setText("Start Translating");
        bt_starttranslating.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_starttranslating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_starttranslatingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SheetStartLayout = new javax.swing.GroupLayout(SheetStart);
        SheetStart.setLayout(SheetStartLayout);
        SheetStartLayout.setHorizontalGroup(
            SheetStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SheetStartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_starttranslating)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        SheetStartLayout.setVerticalGroup(
            SheetStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SheetStartLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(bt_starttranslating)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        ConstraintSheet.add(SheetStart, "card2");

        SheetConfig.setOpaque(false);

        asalbahasa.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        asalbahasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Language", "Bahasa Indonesia", "English", "Arabic", "German", "France", "Dutch", "Uzbek" }));
        asalbahasa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                asalbahasaItemStateChanged(evt);
            }
        });
        asalbahasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalbahasaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel9.setText("To");

        hasilbahasa.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        hasilbahasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Language", "Bahasa Indonesia", "English", "Arabic", "German", "France", "Japan", "Dutch", "Uzbek" }));
        hasilbahasa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hasilbahasaItemStateChanged(evt);
            }
        });

        wklikttranslate.setInheritsPopupMenu(true);
        wklikttranslate.setkBorderRadius(20);
        wklikttranslate.setkEndColor(new java.awt.Color(255, 255, 255));
        wklikttranslate.setkStartColor(new java.awt.Color(255, 255, 255));
        wklikttranslate.setOpaque(false);
        wklikttranslate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wklikttranslateMouseEntered(evt);
            }
        });

        btntranslate.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btntranslate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/icons8-google-translate-64.png"))); // NOI18N
        btntranslate.setText("Translate");
        btntranslate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntranslate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntranslateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout wklikttranslateLayout = new javax.swing.GroupLayout(wklikttranslate);
        wklikttranslate.setLayout(wklikttranslateLayout);
        wklikttranslateLayout.setHorizontalGroup(
            wklikttranslateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wklikttranslateLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(btntranslate)
                .addContainerGap())
        );
        wklikttranslateLayout.setVerticalGroup(
            wklikttranslateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btntranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xtranslator/icons8-swap-60.png"))); // NOI18N
        jLabel10.setText("Swap");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel11.setText("From :");

        btn_clearall.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btn_clearall.setText("Clear All Sheet");
        btn_clearall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clearall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearallMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SheetConfigLayout = new javax.swing.GroupLayout(SheetConfig);
        SheetConfig.setLayout(SheetConfigLayout);
        SheetConfigLayout.setHorizontalGroup(
            SheetConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SheetConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SheetConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SheetConfigLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(196, 196, 196))
                    .addGroup(SheetConfigLayout.createSequentialGroup()
                        .addGroup(SheetConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asalbahasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hasilbahasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(SheetConfigLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(SheetConfigLayout.createSequentialGroup()
                .addGroup(SheetConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SheetConfigLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(SheetConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(btn_clearall)))
                    .addGroup(SheetConfigLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(wklikttranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SheetConfigLayout.setVerticalGroup(
            SheetConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SheetConfigLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asalbahasa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasilbahasa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(wklikttranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_clearall)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(40, 40, 40))
        );

        ConstraintSheet.add(SheetConfig, "card2");

        kGradientPanel7.setkBorderRadius(0);
        kGradientPanel7.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel7.setkGradientFocus(1000);
        kGradientPanel7.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/icons8-translation-48.png"))); // NOI18N
        jLabel5.setText("Xtranslator");

        btnclose.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconclose50.png"))); // NOI18N
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
        });

        btnminimize.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-minimize-window-50.png"))); // NOI18N
        btnminimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnminimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclose)
                .addContainerGap())
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnminimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel6.setText("Your daily translator assistance");

        javax.swing.GroupLayout tesdinamisLayout = new javax.swing.GroupLayout(tesdinamis);
        tesdinamis.setLayout(tesdinamisLayout);
        tesdinamisLayout.setHorizontalGroup(
            tesdinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tesdinamisLayout.createSequentialGroup()
                .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tesdinamisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tesdinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tesdinamisLayout.createSequentialGroup()
                        .addComponent(ConstraintSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(tesdinamisLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tesdinamisLayout.setVerticalGroup(
            tesdinamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tesdinamisLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(ConstraintSheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        sheetinput.setBorder(new javax.swing.border.MatteBorder(null));
        sheetinput.setkBorderRadius(40);
        sheetinput.setkEndColor(new java.awt.Color(116, 235, 213));
        sheetinput.setkGradientFocus(900);
        sheetinput.setkStartColor(new java.awt.Color(172, 182, 229));
        sheetinput.setOpaque(false);

        kGradientPanel4.setkBorderRadius(0);
        kGradientPanel4.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel4.setkGradientFocus(1000);
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 255, 255));

        kGradientPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        kGradientPanel6.setkBorderRadius(0);
        kGradientPanel6.setkEndColor(new java.awt.Color(112, 225, 245));
        kGradientPanel6.setkStartColor(new java.awt.Color(255, 209, 148));

        indikatorinput.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        indikatorinput.setText("Input Language");

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indikatorinput, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indikatorinput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addComponent(kGradientPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        inputpane.setColumns(20);
        inputpane.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        inputpane.setRows(5);
        scrollinput.setViewportView(inputpane);

        labelinput1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        labelinput1.setText("Type your word here :");

        javax.swing.GroupLayout sheetinputLayout = new javax.swing.GroupLayout(sheetinput);
        sheetinput.setLayout(sheetinputLayout);
        sheetinputLayout.setHorizontalGroup(
            sheetinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
            .addGroup(sheetinputLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(sheetinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelinput1)
                    .addComponent(scrollinput, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        sheetinputLayout.setVerticalGroup(
            sheetinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sheetinputLayout.createSequentialGroup()
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(labelinput1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollinput, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        kGradientPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        kGradientPanel3.setkBorderRadius(40);
        kGradientPanel3.setkEndColor(new java.awt.Color(172, 182, 229));
        kGradientPanel3.setkStartColor(new java.awt.Color(116, 235, 213));
        kGradientPanel3.setOpaque(false);

        kGradientPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        kGradientPanel5.setkBorderRadius(0);
        kGradientPanel5.setkEndColor(new java.awt.Color(255, 209, 148));
        kGradientPanel5.setkStartColor(new java.awt.Color(112, 225, 245));

        indikatoroutput.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        indikatoroutput.setText("Output Language");

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(indikatoroutput)
                .addContainerGap())
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indikatoroutput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outputpane.setColumns(20);
        outputpane.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        outputpane.setRows(5);
        scrolloutput.setViewportView(outputpane);

        labelinput2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        labelinput2.setText("See the result here :");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelinput2)
                    .addComponent(scrolloutput, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(labelinput2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrolloutput, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sheetinput, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tesdinamis, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sheetinput, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tesdinamis, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_starttranslatingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_starttranslatingMouseClicked
        // TODO add your handling code here:

        ConstraintSheet.removeAll();
        ConstraintSheet.repaint();
        ConstraintSheet.revalidate();

        ConstraintSheet.add(SheetConfig);
        ConstraintSheet.repaint();
        ConstraintSheet.revalidate();
    }//GEN-LAST:event_bt_starttranslatingMouseClicked

    private void asalbahasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asalbahasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asalbahasaActionPerformed

    private void btntranslateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntranslateMouseClicked
        Translator http = new Translator();
        String ip = null, op = null;
        String input = String.valueOf(asalbahasa.getSelectedItem());
        //            Choose Language, Bahasa Indonesia, English, Arabic, German
        if (input.equals("Bahasa Indonesia")) {
            ip = "id";
        }
        if (input.equals("English")) {
            ip = "en";
        }
        if (input.equals("Arabic")) {
            ip = "ar";
        }
        if (input.equals("German")) {
            ip = "de";
        }
        if (input.equals("France")) {
            ip = "fr";
        }
        if (input.equals("Sunda")) {
            ip = "su";
        }
        if (input.equals("Japan")) {
            ip = "ja";
        }
        if (input.equals("Uzbek")) {
            ip = "uz";
        }
        if (input.equals("Dutch")) {
            ip = "nl";
        }

        String output = String.valueOf(hasilbahasa.getSelectedItem());
        if (output.equals("Bahasa Indonesia")) {
            op = "id";
        }
        if (output.equals("English")) {
            op = "en";
        }
        if (output.equals("Arabic")) {
            op = "ar";
        }
        if (output.equals("German")) {
            op = "de";
        }
        if (output.equals("France")) {
            op = "fr";
        }
        if (output.equals("Japan")) {
            op = "ja";
        }
        if (output.equals("Uzbek")) {
            op = "uz";
        }
        if (output.equals("Dutch")) {
            op = "nl";
        }

        try {
            String masukan = inputpane.getText();
            String word = http.callUrlAndParseResult(ip, op, masukan);
            outputpane.setText(word);
        } catch (Exception ex) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btntranslateMouseClicked

    private void wklikttranslateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wklikttranslateMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_wklikttranslateMouseEntered

    private void asalbahasaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_asalbahasaItemStateChanged
        // TODO add your handling code here:
        String inputan = String.valueOf(asalbahasa.getSelectedItem());
        if (inputan.equals("Choose Language")) {
            indikatorinput.setText("Input Language");
        }
        indikatorinput.setText(inputan);

    }//GEN-LAST:event_asalbahasaItemStateChanged

    private void hasilbahasaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hasilbahasaItemStateChanged
        // TODO add your handling code here:
        String outputan = String.valueOf(hasilbahasa.getSelectedItem());
        indikatoroutput.setText(outputan);
        if (outputan.equals("Choose Language")) {
            indikatoroutput.setText("Input Language");
        }

    }//GEN-LAST:event_hasilbahasaItemStateChanged

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        String inp = indikatorinput.getText();
        String out = indikatoroutput.getText();

        indikatorinput.setText(out);
        indikatoroutput.setText(inp);

        String inp2 = String.valueOf(asalbahasa.getSelectedItem());
        String out2 = String.valueOf(hasilbahasa.getSelectedItem());

        asalbahasa.setSelectedItem(out2);
        hasilbahasa.setSelectedItem(inp2);

        String inp3 = inputpane.getText();
        String out3 = outputpane.getText();

        inputpane.setText(out3);
        terjemah();

    }//GEN-LAST:event_jLabel10MouseClicked

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btncloseMouseClicked

    private void btnminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnminimizeMouseClicked

    private void btn_clearallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearallMouseClicked
        // TODO add your handling code here:
        inputpane.setText("");
        outputpane.setText("");
        asalbahasa.setSelectedItem("Choose Language");
        asalbahasa.setSelectedItem("Choose Language");

    }//GEN-LAST:event_btn_clearallMouseClicked
    public String callUrlAndParseResult(String langFrom, String langTo, String word) throws Exception {

        String url = "https://translate.googleapis.com/translate_a/single?"
                + "client=gtx&"
                + "sl=" + langFrom
                + "&tl=" + langTo
                + "&dt=t&q=" + URLEncoder.encode(word, "UTF-8");

        URL obj = new URL(url);
        HttpURLConnection con = (HttpURLConnection) obj.openConnection();
        con.setRequestProperty("User-Agent", "Mozilla/5.0");

        BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream()));
        String inputLine;
        StringBuffer response = new StringBuffer();

        while ((inputLine = in.readLine()) != null) {
            response.append(inputLine);
        }
        in.close();

        return parseResult(response.toString());
    }

    private String parseResult(String inputJson) throws Exception {

        JSONArray jsonArray = new JSONArray(inputJson);
        JSONArray jsonArray2 = (JSONArray) jsonArray.get(0);
        JSONArray jsonArray3 = (JSONArray) jsonArray2.get(0);

        return jsonArray3.get(0).toString();
    }

    public void terjemah() {
        Translator http = new Translator();
        String ip = null, op = null;
        String input = String.valueOf(asalbahasa.getSelectedItem());
        //            Choose Language, Bahasa Indonesia, English, Arabic, German
        if (input.equals("Bahasa Indonesia")) {
            ip = "id";
        }
        if (input.equals("English")) {
            ip = "en";
        }
        if (input.equals("Arabic")) {
            ip = "ar";
        }
        if (input.equals("German")) {
            ip = "de";
        }
        if (input.equals("France")) {
            ip = "fr";
        }
        if (input.equals("Sunda")) {
            ip = "su";
        }
        if (input.equals("Japan")) {
            ip = "ja";
        }

        String output = String.valueOf(hasilbahasa.getSelectedItem());
        if (output.equals("Bahasa Indonesia")) {
            op = "id";
        }
        if (output.equals("English")) {
            op = "en";
        }
        if (output.equals("Arabic")) {
            op = "ar";
        }
        if (output.equals("German")) {
            op = "de";
        }
        if (output.equals("Sunda")) {
            op = "su";
        }
        if (output.equals("France")) {
            op = "fr";
        }
        if (output.equals("Japan")) {
            op = "ja";
        }

        try {

            String masukan = inputpane.getText();
            String word = http.callUrlAndParseResult(ip, op, masukan);
            outputpane.setText(word);
        } catch (Exception ex) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTranslator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTranslator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTranslator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTranslator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTranslator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConstraintSheet;
    private javax.swing.JPanel SheetConfig;
    private javax.swing.JPanel SheetStart;
    private javax.swing.JComboBox<String> asalbahasa;
    private javax.swing.JLabel bt_starttranslating;
    private javax.swing.JLabel btn_clearall;
    private javax.swing.JLabel btnclose;
    private javax.swing.JLabel btnminimize;
    private javax.swing.JLabel btntranslate;
    private javax.swing.JComboBox<String> hasilbahasa;
    private javax.swing.JLabel indikatorinput;
    private javax.swing.JLabel indikatoroutput;
    private javax.swing.JTextArea inputpane;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private javax.swing.JLabel labelinput1;
    private javax.swing.JLabel labelinput2;
    private javax.swing.JTextArea outputpane;
    private javax.swing.JScrollPane scrollinput;
    private javax.swing.JScrollPane scrolloutput;
    private keeptoo.KGradientPanel sheetinput;
    private keeptoo.KGradientPanel tesdinamis;
    private keeptoo.KGradientPanel wklikttranslate;
    // End of variables declaration//GEN-END:variables
}
